Make README more useful
ARMmbed/mbed-os-example-socket-stats pull request #45
Opened 2020-02-07 13:41 UTC by rajkan01

* Provide description on application functionality
* Add official example badge
* Remove outdated information
* Link to Mbed boards
* Indicate how to find out which toolchain support a target chosen
* Provide instructions to flash after building
* Updated the tests README to give proper information with example

2020-02-10 18:23 UTC, evedon requested changes

2020-02-10 18:23 UTC, evedon commented on README.md
> +## Network interface and Socket statistics target configuration
The content of this section should move under `Application functionality`

2020-02-10 18:23 UTC, evedon commented on README.md
> +This guide reviews the steps required to get socket statistics on an Mbed OS enabled platform.
```suggestion
This example demonstrates how you can collect statistics from network sockets on an Mbed OS enabled platform.
```

2020-02-10 18:23 UTC, evedon commented on README.md
> +
You can enable socket statistics by setting `nsapi.socket-stats-enabled` to true in `mbed_app.json`: _give example_

2020-02-10 18:23 UTC, evedon commented on README.md
> +
The current example is configured to use the Ethernet interface on supported devices. To use the example with a different interface, please follow the [socket example readme](https://github.com/ARMmbed/mbed-os-example-sockets/blob/master/README.md).

2020-02-10 18:23 UTC, evedon commented on README.md
> +* [Mbed OS configuration](https://os.mbed.com/docs/latest/reference/configuration.html).
Also add:   [Network interfaces](https://os.mbed.com/docs/latest/apis/network-interfaces.html)

2020-02-10 18:23 UTC, evedon commented on README.md
> +The `main()` function gets the default instance of a network interface and set up the socket connection. It also starts a thread to print socket statistics such as  `reference_id`, `state`, `proto`,
```suggestion
The `main()` function opens a socket on the Ethernet interface and creates a TCP connection to generate some data traffic. It also starts a thread to periodically print socket statistics such as  `reference_id`, `state`, `proto`, `sent_bytes`, `recv_bytes`, `last_change_tick` on the console.
```

2020-02-10 18:23 UTC, evedon commented on main.cpp
> +            printf("Num: %d   ", num);
I would suggest to rename Num to `Iteration`

2020-02-10 18:23 UTC, evedon commented on main.cpp
>      p = strstr(buffer, "\r\n\r\n") + 4;
This is no longer needed if you are not going to print the external IP address.

2020-02-10 18:23 UTC, evedon commented on main.cpp
>      delete[] buffer;
I think that `buffer` can be removed if you take my earlier comment.

2020-02-11 11:50 UTC, evedon commented on README.md
> +The `main()` function opens a socket on the Ethernet interface and creates a TCP connection to generate some data traffic. It also starts a thread to periodically print socket statistics such as  `re
You should use the variable names shown in the console, so `ID`, `State` etc.

2020-02-11 11:50 UTC, evedon commented on README.md
> +Iteration:      Number of times socket state changes and repeated the same value to indicate TCP and UDP
```suggestion
Iteration:      Number of times socket state changes
```

2020-02-11 11:57 UTC, evedon approved these changes

2020-02-11 22:07 UTC, AnotherButler approved these changes
Thanks for the PR 👍

2020-02-12 09:41 UTC, merged